### ISSUE TITLE
Preconditions when adding custom models

### ISSUE THREAD

**Issue by fanavarro** [mitvis/embedding-comparator#2]
Hi, I would like to compare some custom models I have, but I am wondering if there are any requirements or preconditions for that. For example:

- Should the models have the same vocabulary? What happened if there are words in a model that are not appearing in the other one?
- Is it important the order in which the vectors are stored in the TSV files to be processed by the `preprocess_data.py` script?

Thanks in advance.

**Comment by aboggust** [comment]
Hi, thanks for your interest in the Embedding Comparator!

To answer your questions:

* Yes, the models do need to have the same vocabulary. Or at least your analysis has to be over the same set of embedded objects. The embedding comparator relies on a local neighborhood similarity metric that compares the neighbors of an embedded object (e.g., word) in both models’ embedding spaces. So, the similarity of an object that only exists in one embedding space will be undefined.
* `preprocess_data.py` takes in an `embeddings_file` containing a embeddings of each word and a `metadata_file` containing the words mapped to each embedding. Those two files need to be in the same order, such that each word (`metadata_file[i]`) maps to its embedding (`embeddings_file[i]`). The order should also be same same for each model you are processing. So if want to compare model A and model B, model A's `embeddings_file` should be in the same order as model B’s `embedding_file`.

**Comment by fanavarro** [comment]
Hi @aboggust, thanks for your quick answer! Everything is clear for me now, I'm closing the issue.

Thanks!
